### ISSUE TITLE
Duplicate dialogs and application still crashes

### ISSUE THREAD

**Issue by cheynewallace** [sindresorhus/electron-unhandled#14]
Iv added `electron-unhandled` to my app, although now I just get two dialogs,  the default one, showing the stacktrace and error, and then the dialog from electron-unhandled, and then the application still crashes.

I just want to display the one dialog, from electron-unhandled and not have the app crash.  

How can I do this?

**Comment by sindresorhus** [comment]
What Electron version are you using? If not the latest, can you try with the latest? And can you share a screenshot of the error dialogs you get?
