### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by armaldio** [sindresorhus/electron-unhandled#2]
A little 'copy to clipboard' button to allow the user to copy the error log for easy report

Maybe with `showMessageBox` instead of `showErrorBox`

`options` take an array of buttons
https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback

**Comment by sindresorhus** [comment]
Yes, that's a good idea. I went with `showErrorBox` because `showMessageBox` didn't seem to work if it's called right at startup before the `app.on('read')` event. But we can work around that by using `showErrorBox` before `app.on('read')` and `showMessageBox` after.

Pull request welcome :)

**Comment by armaldio** [comment]
I've made a pull request to sove this :)

https://github.com/sindresorhus/electron-unhandled/pull/3
