### ISSUE TITLE
Serialized error return Buffer and it is unreadable.

### ISSUE THREAD

**Issue by erdkse** [sindresorhus/electron-unhandled#26]
I would like to see the error in readable format.

<img width="870" alt="Screen Shot 2022-03-04 at 05 59 37" src="https://user-images.githubusercontent.com/2957624/156690860-69014fbe-13f0-4e93-933e-ef63732bbc36.png">

**Comment by sindresorhus** [comment]
Probably caused by https://github.com/sindresorhus/electron-unhandled/commit/3220f094c916b2f50ddc4527419be799929784fb

// @Slapbox

**Comment by erdkse** [comment]
Here is an example error that is serialized into BufferArray! Because it is uninvokable the library tries it to serialize and it ends up with a BufferArray result.

If you want I can create a PR that specifically handles ErrorEvent types errors?

![Screen Shot 2022-03-04 at 10 44 55](https://user-images.githubusercontent.com/2957624/156720988-cba09caa-b68c-4767-9d62-6f14a3f985eb.png)

**Comment by sindresorhus** [comment]
Sure, PR welcome.
